apiVersion: v1
kind: Secret
metadata:
  name: pypy-secrets
  namespace: default
type: Opaque
data:
  # base64 of pypy_db_secure_password
  DATABASE_PASSWORD: cHlweV9kYl9zZWN1cmVfcGFzc3dvcmQ=
  # base64 of super_secret_pypy_jwt_key
  JWT_SECRET: c3VwZXJfc2VjcmV0X3B5cHlfand0X2tleQ==
