// Isolated UI contract tests. All WebSocket messages stay inside Playwright;
// these fixtures are never bundled into the dashboard or sent to PYPY.
// Run with PLAYWRIGHT_MODULE pointing to an installed playwright/index.mjs.
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const origin = process.env.EXHIBITION_URL || 'http://localhost:5173';
const topologyResponse = await page.request.get('http://localhost:8000/api/telemetry/topology?grid_name=ieee39');
assert.equal(topologyResponse.ok(), true, 'Read actual topology for test connectivity');
const topology = await topologyResponse.json();
await page.route('**/api/telemetry/topology?*', route => route.fulfill({json:topology}));
let socket; const commands = [];
const frame = () => ({ timestamp:Date.now(), grid_name:'ieee39', experiment_id:'browser-test', solver_status:{converged:true}, attack_status:{active_attack:null,compromised_nodes:{}}, state:{buses:Object.fromEntries(Object.keys(topology.buses).map(id=>[id,{voltage_pu:1,load_mw:10}])),lines:Object.fromEntries(topology.lines.map(l=>[l.id,{active_power_flow:20,loading_percent:30}])),breakers:Object.fromEntries(topology.lines.map(l=>[l.id,'CLOSED']))} });
let current = frame();
await page.routeWebSocket('**/ws', ws => {
  socket = ws;
  ws.onMessage(message => { const data=JSON.parse(message);if(data.topic) commands.push(data); });
  ws.send(JSON.stringify({type:'BOOTSTRAP',telemetry:current,events:[],alerts:[]}));
});
const send = (topic,payload) => socket.send(JSON.stringify({topic,payload}));
await page.goto(`${origin}/#/exhibition`);
await page.waitForSelector('.ex-bus');
await page.waitForFunction(()=>document.querySelector('h1')?.textContent==='GRID STABLE · MONITORING');
send('grid/ai/status/lstm',{timestamp:Date.now(),ready:true});
send('grid/trust_scores',{timestamp:Date.now(),global_grid_confidence:.98});
await page.waitForFunction(()=>document.querySelector('.ex-defense')?.textContent.includes('1 models ready'));
assert.equal(await page.locator('.ex-stage').nth(2).getAttribute('class'),'ex-stage ex-info');
const dimensions = async (width,height) => {
  await page.setViewportSize({width,height}); await page.evaluate(()=>document.fonts.ready); await page.waitForTimeout(100);
  const size=await page.evaluate(()=>({w:innerWidth,h:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,defense:document.querySelector('.ex-defense').getBoundingClientRect().bottom,challenge:document.querySelector('.ex-challenge').getBoundingClientRect().top}));
  assert.ok(size.sw<=width,`No horizontal overflow at ${width}: ${JSON.stringify(size)}`);
  if(width>=1100 && height>=768) assert.ok(size.sh<=height,`No vertical overflow at ${width}: ${JSON.stringify(size)}`);
  assert.ok(size.defense<=size.challenge+1 || width<700,'Defence and CTA do not overlap');
  if(width>=1100) {const bounds=await page.evaluate(()=>({cta:document.querySelector('.ex-challenge').getBoundingClientRect().bottom,pipeline:document.querySelector('.ex-pipeline').getBoundingClientRect().top}));await page.screenshot({path:'/tmp/pypy-exhibition-current.png'});assert.ok(bounds.cta<=bounds.pipeline,`CTA does not overlap pipeline ${JSON.stringify(bounds)}`);}
  console.log('Layout',width,height,size);
};
await dimensions(1920,1080);
await page.screenshot({path:'/tmp/pypy-exhibition-live-test.png'});
await dimensions(1366,768);await page.screenshot({path:'/tmp/pypy-exhibition-laptop-test.png'});
await dimensions(1440,900);await dimensions(390,844);await page.screenshot({path:'/tmp/pypy-exhibition-mobile-test.png',fullPage:true});
await dimensions(1920,1080);
await page.getByRole('button',{name:'Unmute',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'Mute',exact:true}).getAttribute('aria-pressed'),'true');
await page.getByRole('button',{name:'Mute',exact:true}).click();
await page.getByRole('button',{name:'Enter fullscreen',exact:true}).click();
await page.waitForFunction(()=>!!document.fullscreenElement);
await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
await page.getByRole('button',{name:'LAUNCH CYBER ATTACK',exact:true}).click();
assert.equal(await page.locator('dialog').evaluate(d=>d.open),true);
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('button',{name:'LAUNCH CYBER ATTACK',exact:true}).evaluate(b=>b===document.activeElement),true);
await page.getByRole('button',{name:'LAUNCH CYBER ATTACK',exact:true}).click();
await page.getByRole('button',{name:'Launch selected attack',exact:true}).click();
await page.waitForTimeout(100);
assert.equal(commands.at(-1).topic,'grid/attack');
assert.deepEqual(commands.at(-1).payload.config,{target:'Bus_5',bias:.15,scale:1});
current=frame();current.attack_status={active_attack:'FDIA',compromised_nodes:{Bus_5:{type:'FDIA'}}};send('pypy/grid/telemetry',current);
send('grid/alerts',{timestamp:Date.now(),type:'GRID_DEVIATION',suspect_node:'Bus_5',severity:'CRITICAL'});
await page.waitForFunction(()=>document.querySelector('h1')?.textContent==='CYBER ATTACK IN PROGRESS');
assert.equal(await page.locator('.ex-stage').nth(1).getAttribute('class'),'ex-stage ex-warning');
await page.screenshot({path:'/tmp/pypy-exhibition-attack-test.png'});
await page.getByRole('button',{name:'STOP ATTACK',exact:true}).click();
await page.waitForTimeout(100);assert.deepEqual(commands.at(-1).payload,{action:'STOP'});
current=frame();send('pypy/grid/telemetry',current);
await page.waitForFunction(()=>document.querySelector('h1')?.textContent!=='CYBER ATTACK IN PROGRESS');
assert.notEqual(await page.locator('h1').textContent(),'GRID SECURED');
await page.getByRole('button',{name:'LAUNCH CYBER ATTACK',exact:true}).click();
await page.getByRole('button',{name:/Breaker manipulation/}).click();
await page.getByRole('button',{name:'Launch selected attack',exact:true}).click();
await page.waitForTimeout(100);assert.deepEqual(commands.at(-1).payload.config,{target:'L_line_0',command:'OPEN'});
current=frame();current.attack_status={active_attack:'BREAKER_MANIPULATION',compromised_nodes:{L_line_0:{type:'BREAKER_MANIPULATION'}}};current.state.breakers.L_line_0='OPEN';send('pypy/grid/telemetry',current);
await page.waitForFunction(()=>document.querySelector('h1')?.textContent==='CYBER ATTACK IN PROGRESS');
await page.getByRole('button',{name:'STOP ATTACK',exact:true}).click();await page.waitForTimeout(100);
current=frame();current.state.breakers.L_line_0='OPEN';send('pypy/grid/telemetry',current);
const proposal={timestamp:Date.now(),correlation_id:'ui-test',experiment_id:'browser-test',target:'L_line_0',command:'CLOSE',initial_state:'OPEN',source:'AI_RL_PPO_DQN_CONSENSUS',sandbox:{overall_safe:true,solver_converged:true,voltage_safe:true,thermal_safe:true,topology_valid:true,cascade_safe:true,finite_state:true}};
send('grid/control/proposed',proposal);
send('grid/orchestrator/events',{...proposal,event:'REJECTION',reason:'Test safety condition failed'});
await page.waitForFunction(()=>document.querySelector('h1')?.textContent==='UNSAFE RESPONSE BLOCKED');
send('grid/orchestrator/events',{...proposal,timestamp:Date.now()+1,event:'APPROVAL',reason:'Test approved'});
await page.waitForTimeout(10);
const {timestamp: _sourceTime, ...control}=proposal;
send('grid/control',{...control,source:'ORCHESTRATOR_APPROVED'});
await page.waitForTimeout(50);current=frame();current.state.buses.Bus_36.voltage_pu=1.0636;send('pypy/grid/telemetry',current);
await page.waitForFunction(()=>document.querySelector('h1')?.textContent==='GRID SECURED');
await page.screenshot({path:'/tmp/pypy-exhibition-recovery-test.png'});
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('.ex-flow').first().evaluate(e=>getComputedStyle(e).animationName),'none');
await page.clock.install();await page.keyboard.press('Shift');await page.clock.fastForward(46000);
await page.waitForFunction(()=>!!document.querySelector('.ex-attract'));
assert.ok(await page.locator('.ex-attract').count());
const count=commands.length;await page.clock.fastForward(8000);assert.equal(commands.length,count,'Attract never sends controls');
await page.keyboard.press('Shift');assert.equal(await page.locator('.ex-attract').count(),0);
assert.equal(await page.locator('h1').textContent(),'TELEMETRY UNAVAILABLE');
current=frame();current.timestamp=await page.evaluate(()=>Date.now());send('pypy/grid/telemetry',current);
await page.waitForFunction(()=>document.querySelector('.ex-launch')?.disabled===false);
await page.getByRole('button',{name:'LAUNCH CYBER ATTACK',exact:true}).click();
await page.getByRole('button',{name:'Launch selected attack',exact:true}).click();
await page.clock.fastForward(16000);
await page.waitForFunction(()=>document.querySelector('.ex-notice')?.textContent.includes('Command not confirmed'));
assert.match(await page.locator('.ex-notice').innerText(),/Command not confirmed/);
socket.close();await page.clock.fastForward(1000);
await page.waitForFunction(()=>document.querySelector('h1')?.textContent==='CONNECTION LOST');
assert.equal(await page.locator('h1').textContent(),'CONNECTION LOST');
await page.getByRole('link',{name:/Exit Exhibition Mode/}).click();
assert.equal(await page.locator('[data-control-page="overview"]').count(),1);
await page.getByRole('link',{name:'Exhibition Mode',exact:false}).click();
await page.reload();await page.waitForSelector('[data-testid="exhibition"]');
await page.route('**/api/telemetry/topology?*', route => route.fulfill({status:503,body:'Unavailable'}));
await page.reload();await page.waitForSelector('.ex-empty');
await page.waitForFunction(()=>document.querySelector('.ex-empty')?.textContent.includes('503'));
await page.route('**/api/telemetry/topology?*', route => route.fulfill({json:topology}));
await page.getByRole('button',{name:'Retry topology',exact:true}).click();await page.waitForSelector('.ex-bus');
assert.deepEqual(errors,[]);
console.log('PASS: routes, refresh, sizes, attacks, STOP, rejection, recovery, stale/offline, command timeout, audio, fullscreen, dialog focus, attract and reduced motion.');
await browser.close();
